import { WorkOrdersOpenCasesRow } from "@/lib/excel/work-orders-open-cases-parser";

export const sampleWorkOrdersOpenCasesRows: WorkOrdersOpenCasesRow[] = [
  {
    workOrderNumber: "WO0028102",
    workOrderState: "Assigned",
    workOrderScheduledStart: "2026-04-06T09:00:00-04:00",
    workOrderWorkNotes:
      "Replacement Logitech Rally camera delivered via FedEx tracking 870006321610. Technician to verify camera power and test meeting functionality onsite.",
    workOrderAssignmentGroup: "TEK Systems",
    workOrderAssignedTo: "Brian Fritz",
    caseNumber: "CS0062967",
    caseState: "Awaiting Info",
    caseAssignmentGroup: "US_ServiceDesk_WorkplaceAVE_L1",
    account: "THE VANGUARD GROUP, INC.",
    siteName: "OM - Morgan Building - 300 Admiral Nelson Dr",
    caseShortDescription: "Level 2: INC3737136 - Malvern, PA - OM - 300A - Morgan Building - Camera not functioning",
    street: "300 Admiral Nelson Dr Morgan Building",
    city: "Malvern",
    stateOrProvince: "PA",
    zipOrPostalCode: "19355",
    country: "United States",
    priority: "2 - High",
    contactName: "Edward Dougherty 5th",
    email: "edward_dougherty@vanguard.com",
    mobilePhone: "",
    businessPhone: "4846188369",
    contract: "36421",
    entitlement: "US Block of Funds - All Sites - 2025-2026 (YR2) RENEW",
    commentsAndWorkNotes:
      "Replacement unit shipped and tracking shared. Awaiting client confirmation after install. Prior onsite visit did not fully resolve the issue."
  },
  {
    workOrderNumber: "WO0028349",
    workOrderState: "Work In Progress",
    workOrderScheduledStart: "2026-04-08T13:30:00-04:00",
    workOrderWorkNotes:
      "Return visit requested after first onsite appointment. Need client sign-off once replacement camera is validated and firmware is updated.",
    workOrderAssignmentGroup: "TEK Systems",
    workOrderAssignedTo: "Brian Fritz",
    caseNumber: "CS0062967",
    caseState: "Awaiting Info",
    caseAssignmentGroup: "US_ServiceDesk_WorkplaceAVE_L1",
    account: "THE VANGUARD GROUP, INC.",
    siteName: "OM - Morgan Building - 300 Admiral Nelson Dr",
    caseShortDescription: "Level 2: INC3737136 - Malvern, PA - OM - 300A - Morgan Building - Camera not functioning",
    street: "300 Admiral Nelson Dr Morgan Building",
    city: "Malvern",
    stateOrProvince: "PA",
    zipOrPostalCode: "19355",
    country: "United States",
    priority: "2 - High",
    contactName: "Edward Dougherty 5th",
    email: "edward_dougherty@vanguard.com",
    mobilePhone: "",
    businessPhone: "4846188369",
    contract: "36421",
    entitlement: "US Block of Funds - All Sites - 2025-2026 (YR2) RENEW",
    commentsAndWorkNotes:
      "Case remains open after two dispatches. Client reported the issue is still not solved and requested another onsite validation."
  },
  {
    workOrderNumber: "WO0028242",
    workOrderState: "Assigned",
    workOrderScheduledStart: "2026-04-07T16:30:00-04:00",
    workOrderWorkNotes:
      "Scheduled rack power down window confirmed. Danielle to remote in, verify control processor scripts, and coordinate with onsite staff for restart testing.",
    workOrderAssignmentGroup: "Diversified Internal",
    workOrderAssignedTo: "Danielle Moss",
    caseNumber: "CS0065211",
    caseState: "Assigned",
    caseAssignmentGroup: "US_ServiceDesk_WorkplaceAVE_L2",
    account: "Christie's Inc",
    siteName: "New York - Boardroom",
    caseShortDescription: "New York, NY - Boardroom - Scheduled rack power down",
    street: "20 Rockefeller Plaza",
    city: "New York",
    stateOrProvince: "NY",
    zipOrPostalCode: "10020",
    country: "United States",
    priority: "3 - Moderate",
    contactName: "Alicia Torres",
    email: "alicia.torres@christies.com",
    mobilePhone: "",
    businessPhone: "2125550110",
    contract: "51510",
    entitlement: "Managed Service Contract",
    commentsAndWorkNotes:
      "Client approved after-hours outage window. If processor behavior persists, escalate remote support and programming review."
  },
  {
    workOrderNumber: "WO0028243",
    workOrderState: "Assigned",
    workOrderScheduledStart: "2026-04-09T08:00:00-04:00",
    workOrderWorkNotes:
      "Second onsite touch planned if rack reboot does not stabilize the boardroom. Keep programming support on standby and capture validation results.",
    workOrderAssignmentGroup: "Diversified Internal",
    workOrderAssignedTo: "Danielle Moss",
    caseNumber: "CS0065211",
    caseState: "Assigned",
    caseAssignmentGroup: "US_ServiceDesk_WorkplaceAVE_L2",
    account: "Christie's Inc",
    siteName: "New York - Boardroom",
    caseShortDescription: "New York, NY - Boardroom - Scheduled rack power down",
    street: "20 Rockefeller Plaza",
    city: "New York",
    stateOrProvince: "NY",
    zipOrPostalCode: "10020",
    country: "United States",
    priority: "3 - Moderate",
    contactName: "Alicia Torres",
    email: "alicia.torres@christies.com",
    mobilePhone: "",
    businessPhone: "2125550110",
    contract: "51510",
    entitlement: "Managed Service Contract",
    commentsAndWorkNotes:
      "This case may require a repeat visit if boardroom stability is not confirmed after the first outage window."
  },
  {
    workOrderNumber: "WO0028064",
    workOrderState: "Assigned",
    workOrderScheduledStart: "2026-04-06T17:00:00-04:00",
    workOrderWorkNotes:
      "Raleigh executive boardroom camera offline. Need switchport and VLAN review with RCE before technician sign-off.",
    workOrderAssignmentGroup: "TEK Systems",
    workOrderAssignedTo: "Theo Bennett",
    caseNumber: "CS0062678",
    caseState: "Awaiting Info",
    caseAssignmentGroup: "US_ServiceDesk_WorkplaceAVE_L1",
    account: "AmeriHealth Caritas",
    siteName: "Raleigh - Executive Boardroom 565",
    caseShortDescription: "Raleigh, NC - Executive Boardroom 565 - Camera offline",
    street: "1100 Wellness Way",
    city: "Raleigh",
    stateOrProvince: "NC",
    zipOrPostalCode: "27609",
    country: "United States",
    priority: "2 - High",
    contactName: "Karen Willis",
    email: "karen.willis@amerihealth.com",
    mobilePhone: "",
    businessPhone: "9195550199",
    contract: "41822",
    entitlement: "Break/Fix Support",
    commentsAndWorkNotes:
      "Client IT needs to validate network settings. Schedule RCE support remotely if camera remains offline."
  },
  {
    workOrderNumber: "WO0028341",
    workOrderState: "Assigned",
    workOrderScheduledStart: "2026-04-07T09:00:00-05:00",
    workOrderWorkNotes:
      "Requesting quote for replacing the projector lamp. Awaiting client approval before dispatch can proceed.",
    workOrderAssignmentGroup: "TEK Systems",
    workOrderAssignedTo: "Patrick Shea",
    caseNumber: "CS0056992",
    caseState: "Awaiting Approval",
    caseAssignmentGroup: "US_ServiceDesk_WorkplaceAVE_L1",
    account: "AMSURG, LLC",
    siteName: "TN - 1A Burton Hills Blvd - Room 1604",
    caseShortDescription: "Nashville, TN - Room 1604 - Requesting quote for replacing projector lamp",
    street: "1 Burton Hills Blvd",
    city: "Nashville",
    stateOrProvince: "TN",
    zipOrPostalCode: "37215",
    country: "United States",
    priority: "3 - Moderate",
    contactName: "Cory Evans",
    email: "cory.evans@amsurg.com",
    mobilePhone: "",
    businessPhone: "6155550133",
    contract: "55701",
    entitlement: "Time and Materials",
    commentsAndWorkNotes:
      "Estimate sent. Need PO or approval before parts are ordered and delivery ETA can be shared."
  },
  {
    workOrderNumber: "WO0028018",
    workOrderState: "Assigned",
    workOrderScheduledStart: "2026-04-10T10:00:00-04:00",
    workOrderWorkNotes:
      "NDI network issue in Avery 113. Coordinate remote support to review VLAN, Dante routes, and device configuration before onsite closure.",
    workOrderAssignmentGroup: "Diversified Internal",
    workOrderAssignedTo: "Danielle Moss",
    caseNumber: "CS0059433",
    caseState: "Assigned",
    caseAssignmentGroup: "US_ServiceDesk_WorkplaceAVE_L2",
    account: "Columbia University Facilities",
    siteName: "Avery 113 (Wood Auditorium)",
    caseShortDescription: "New York, NY - Avery 113 - NDI network issue",
    street: "1172 Amsterdam Ave",
    city: "New York",
    stateOrProvince: "NY",
    zipOrPostalCode: "10027",
    country: "United States",
    priority: "2 - High",
    contactName: "Jordan Pike",
    email: "jordan.pike@columbia.edu",
    mobilePhone: "",
    businessPhone: "2125550177",
    contract: "62018",
    entitlement: "Campus Service Support",
    commentsAndWorkNotes:
      "Issue appears tied to VLAN configuration and may need one beyond remote support before closure."
  }
];
